# docker volume create rabbitmq
version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    networks:
      - overlay
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=rm
      - RABBITMQ_DEFAULT_USER=rm
      - RABBITMQ_DEFAULT_PASS=rm

volumes:
  rabbitmq:
networks:
  overlay: